In [4]:
import pandas as pd
df = pd.read_csv("data/conflicts_tur_syr_22.csv", delimiter = ",")
df

,data_id,iso,event_id_cnty,event_id_no_cnty,event_date,year,time_precision,event_type,sub_event_type,actor1,...,location,latitude,longitude,geo_precision,source,source_scale,notes,fatalities,timestamp,iso3
0,8325527,760,SYR18098,18098,01 January 2018,2018,1,Battles,Armed clash,QSD: Syrian Democratic Forces,...,Jazaret Elbuhmeid,35.7875,39.7266,1,Liveuamap,Local partner-New media,Regime forces and loyalist militia forces clas...,5,1624916757,SYR
1,8325528,760,SYR18121,18121,01 January 2018,2018,1,Battles,Armed clash,Islamist Militia (Syria),...,Samlin,33.0414,36.0980,1,SOHR,Other,Two Islamist faction fighters were killed in a...,2,1624916757,SYR
2,8325540,760,SYR18104,18104,01 January 2018,2018,1,Battles,Government regains territory,Military Forces of Syria (2000-),...,Khwein Elshaer,35.6969,36.9276,1,SOHR,Other,Regime forces and loyalist militias captured t...,0,1624916757,SYR
3,8325550,760,SYR38,38,01 January 2018,2018,1,Battles,Armed clash,Military Forces of Syria (2000-),...,Talbiseh,34.8427,36.7267,1,SNHR; SOHR,Local partner-Other,Clashes took place between the regime forces a...,2,1624916757,SYR
4,8325555,760,SYR18117,18117,01 January 2018,2018,1,Battles,Government regains territory,Military Forces of Syria (2000-) Tiger Paramil...,...,Sham al-Hawa,35.4844,36.8815,1,Liveuamap,Local partner-New media,Loyalist militia Tiger Force recaptured Sahm a...,0,1624916757,SYR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8772,8356326,760,SYR12,12,01 January 2017,2017,1,Battles,Armed clash,Military Forces of Syria (2000-),...,Deir-ez-Zor - Military Airbase,35.2856,40.1770,1,SOHR,Other,Clashes took place between Syrian regime force...,0,1624916983,SYR
8773,8356344,760,SYR23,23,01 January 2017,2017,1,Battles,Armed clash,Unidentified Armed Group (Syria),...,Kaftin,36.0958,36.6796,1,SOHR,Other,Unidentified gunmen kidnapped five members of ...,0,1624916983,SYR
8774,8754539,760,SYR39257,39257,01 January 2017,2017,1,Battles,Armed clash,Military Forces of Syria (2000-),...,Basimah,33.6040,36.1979,1,SHAAM,National,Syrian regime forces attempted to advance duri...,0,1641867746,SYR
8775,8757446,760,SYR34474,34474,01 January 2017,2017,1,Battles,Armed clash,Military Forces of Syria (2000-),...,Hseiniyeh,33.6094,36.1234,2,SHAAM,National,Syrian regime forces attempted to advance duri...,0,1641867755,SYR
8776,8758088,760,SYR39253,39253,01 January 2017,2017,1,Battles,Armed clash,Opposition Rebels (Syria),...,Duma,33.5706,36.4046,1,SHAAM,National,Clashes took place between rebels and Syrian r...,0,1641867757,SYR

In [35]:
# Split date into day and month
df["event_date"] = pd.to_datetime(df["event_date"])
df['day'] = df ['event_date'].dt.day 
df ['month'] = df ['event_date'].dt.month
df = df.drop("event_date", axis=1)
df

,event_id_cnty,year,time_precision,disorder_type,event_type,sub_event_type,actor1,assoc_actor_1,inter1,actor2,...,longitude,geo_precision,source,source_scale,notes,fatalities,tags,timestamp,day,month
0,SYR109663,2022,1,Political violence,Violence against civilians,Abduction/forced disappearance,National Police Forces,NaN,2,Civilians (Syria),...,36.8655,1,SOHR,Other,"On 31 December 2022, National Police Forces de...",0,NaN,1673305318,31,12
1,SYR109664,2022,2,Political violence,Violence against civilians,Abduction/forced disappearance,Police Forces of Turkey (2016-) National Intel...,NaN,8,Civilians (Syria),...,36.6896,2,SOHR,Other,"Around 31 December 2022 (week of), a Turkish i...",0,NaN,1673305318,31,12
2,SYR109665,2022,1,Political violence,Violence against civilians,Abduction/forced disappearance,QSD: Syrian Democratic Forces,NaN,2,Civilians (Iraq),...,41.1333,1,Facebook; SHAAM,New media-National,"On 31 December 2022, QSD forces detained three...",0,NaN,1673305318,31,12
3,SYR109685,2022,1,Political violence,Violence against civilians,Abduction/forced disappearance,QSD: Syrian Democratic Forces,NaN,2,Civilians (Syria),...,40.5641,1,SOHR,Other,"On 31 December 2022, a QSD patrol stormed a mo...",0,NaN,1673305318,31,12
4,SYR109693,2022,1,Political violence,Violence against civilians,Abduction/forced disappearance,YPG: Peoples Protection Units,NaN,2,Civilians (Syria),...,37.9510,1,Facebook,New media,"On 31 December 2022, YPG forces abducted a 13 ...",0,women targeted: girls,1673305319,31,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11125,SYR97623,2022,1,Political violence,Explosions/Remote violence,Air/drone strike,Military Forces of Russia (2000-),NaN,8,Islamic State (Syria),...,38.7581,2,SHAAM; SOHR; Facebook,Other-New media,"On 1 January 2022, Russian warplanes conducted...",0,NaN,1680570793,1,1
11126,SYR97627,2022,1,Political violence,Explosions/Remote violence,Air/drone strike,Military Forces of Russia (2000-),NaN,8,NaN,...,36.6353,2,SY24; Facebook; SOHR,Other-New media,"On 1 January 2022, Russian warplanes conducted...",0,NaN,1680570793,1,1
11127,SYR97626,2022,1,Political violence,Explosions/Remote violence,Air/drone strike,Military Forces of Russia (2000-),NaN,8,Islamic State (Syria),...,37.7886,2,SOHR,Other,"On 1 January 2022, Russian warplanes conducted...",0,NaN,1680570793,1,1
11128,SYR97628,2022,1,Political violence,Explosions/Remote violence,Air/drone strike,Military Forces of Russia (2000-),NaN,8,NaN,...,36.5418,2,SOHR,Other,"On 1 January 2022, Russian warplanes conducted...",0,NaN,1680570793,1,1
11129,SYR97614,2022,1,Political violence,Violence against civilians,Abduction/forced disappearance,Global Coalition Against Daesh,NaN,8,Civilians (Syria),...,40.2921,2,Facebook; SHAAM,New media-National,"On 1 January 2022, Global Coalition Forces det...",0,NaN,1686096185,1,1

In [37]:
# Extract relevant columns
important_cols = ["event_id_cnty", "day","month","year","location", "latitude", "longitude"]
interesting_data = df[important_cols]
interesting_data

      event_id_cnty  day  month  year         location  latitude  longitude
0         SYR109663   31     12  2022            Afrin   36.5111    36.8655
1         SYR109664   31     12  2022        Jandairis   36.3925    36.6896
2         SYR109665   31     12  2022        Hole Camp   36.3768    41.1333
3         SYR109685   31     12  2022        Al Shanan   34.9708    40.5641
4         SYR109693   31     12  2022           Menbij   36.5258    37.9510
...             ...  ...    ...   ...              ...       ...        ...
11125      SYR97623    1      1  2022       Al-Rasafah   35.6288    38.7581
11126      SYR97627    1      1  2022            Idleb   35.9290    36.6353
11127      SYR97626    1      1  2022        Ithariyah   35.3652    37.7886
11128      SYR97628    1      1  2022  Jabal al-Zawiya   35.7197    36.5418
11129      SYR97614    1      1  2022   Al-Asbah farms   35.3219    40.2921

[11130 rows x 7 columns]

In [10]:
# Export to CSV to be exported to GEOJSON in QGIS
#interesting_data.to_csv("data/Conflicts_Syr_Tur_2022.csv", sep=',')

In [8]:
# Prepare conflict data in Syria in 2017
df2 = pd.read_csv("data/conflicts_syria_2017.csv", delimiter = ";")
df2

,data_id,iso,event_id_cnty,event_id_no_cnty,event_date,year,time_precision,event_type,sub_event_type,actor1,...,location,latitude,longitude,geo_precision,source,source_scale,notes,fatalities,timestamp,iso3
0,8325527,760,SYR18098,18098,01 January 2018,2018,1,Battles,Armed clash,QSD: Syrian Democratic Forces,...,Jazaret Elbuhmeid,35.7875,39.7266,1,Liveuamap,Local partner-New media,Regime forces and loyalist militia forces clas...,5,1624916757,SYR
1,8325528,760,SYR18121,18121,01 January 2018,2018,1,Battles,Armed clash,Islamist Militia (Syria),...,Samlin,33.0414,36.0980,1,SOHR,Other,Two Islamist faction fighters were killed in a...,2,1624916757,SYR
2,8325540,760,SYR18104,18104,01 January 2018,2018,1,Battles,Government regains territory,Military Forces of Syria (2000-),...,Khwein Elshaer,35.6969,36.9276,1,SOHR,Other,Regime forces and loyalist militias captured t...,0,1624916757,SYR
3,8325550,760,SYR38,38,01 January 2018,2018,1,Battles,Armed clash,Military Forces of Syria (2000-),...,Talbiseh,34.8427,36.7267,1,SNHR; SOHR,Local partner-Other,Clashes took place between the regime forces a...,2,1624916757,SYR
4,8325555,760,SYR18117,18117,01 January 2018,2018,1,Battles,Government regains territory,Military Forces of Syria (2000-) Tiger Paramil...,...,Sham al-Hawa,35.4844,36.8815,1,Liveuamap,Local partner-New media,Loyalist militia Tiger Force recaptured Sahm a...,0,1624916757,SYR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8772,8356326,760,SYR12,12,01 January 2017,2017,1,Battles,Armed clash,Military Forces of Syria (2000-),...,Deir-ez-Zor - Military Airbase,35.2856,40.1770,1,SOHR,Other,Clashes took place between Syrian regime force...,0,1624916983,SYR
8773,8356344,760,SYR23,23,01 January 2017,2017,1,Battles,Armed clash,Unidentified Armed Group (Syria),...,Kaftin,36.0958,36.6796,1,SOHR,Other,Unidentified gunmen kidnapped five members of ...,0,1624916983,SYR
8774,8754539,760,SYR39257,39257,01 January 2017,2017,1,Battles,Armed clash,Military Forces of Syria (2000-),...,Basimah,33.6040,36.1979,1,SHAAM,National,Syrian regime forces attempted to advance duri...,0,1641867746,SYR
8775,8757446,760,SYR34474,34474,01 January 2017,2017,1,Battles,Armed clash,Military Forces of Syria (2000-),...,Hseiniyeh,33.6094,36.1234,2,SHAAM,National,Syrian regime forces attempted to advance duri...,0,1641867755,SYR
8776,8758088,760,SYR39253,39253,01 January 2017,2017,1,Battles,Armed clash,Opposition Rebels (Syria),...,Duma,33.5706,36.4046,1,SHAAM,National,Clashes took place between rebels and Syrian r...,0,1641867757,SYR

In [9]:
# Split date into day and month
df2["event_date"] = pd.to_datetime(df2["event_date"])
df2['day'] = df2['event_date'].dt.day 
df2['month'] = df2['event_date'].dt.month
df2 = df2.drop("event_date", axis=1)

# Get conflicts in 2017
df2 = df2[df2.year == 2017]
df2

,data_id,iso,event_id_cnty,event_id_no_cnty,year,time_precision,event_type,sub_event_type,actor1,assoc_actor_1,...,longitude,geo_precision,source,source_scale,notes,fatalities,timestamp,iso3,day,month
18,8325629,760,SYR18023,18023,2017,1,Battles,Armed clash,QSD: Syrian Democratic Forces,Global Coalition Against Daesh; MDA: Deir-ez-Z...,...,40.8392,2,SOHR,Other,The Syrian Democratic Forces and Deir ez-Zor M...,0,1624916757,SYR,31,12
19,8325645,760,SYR18016,18016,2017,1,Battles,Armed clash,Khalid ibn al Walid Army,NaN,...,35.9354,1,SOHR,Other,The rebel and Islamic factions clashed with Kh...,0,1624916757,SYR,31,12
20,8325664,760,SYR18017,18017,2017,1,Battles,Armed clash,Military Forces of Syria (2000-),Militia (Pro-Government),...,37.4568,2,SOHR,Other,The Syrian army supported its loyal gunmen cla...,0,1624916757,SYR,31,12
21,8757311,760,SYR39249,39249,2017,1,Battles,Armed clash,Military Forces of Syria (2000-),NaN,...,36.4897,1,SHAAM,National,The Syrian army clashed with the rebel faction...,0,1641867754,SYR,31,12
22,8325677,760,SYR18007,18007,2017,1,Battles,Armed clash,Opposition Rebels (Syria),Islamist Militia (Syria),...,37.0886,1,SOHR,Other,The rebel and Islamic factions clashed with QS...,0,1624916757,SYR,30,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8772,8356326,760,SYR12,12,2017,1,Battles,Armed clash,Military Forces of Syria (2000-),NaN,...,40.1770,1,SOHR,Other,Clashes took place between Syrian regime force...,0,1624916983,SYR,1,1
8773,8356344,760,SYR23,23,2017,1,Battles,Armed clash,Unidentified Armed Group (Syria),NaN,...,36.6796,1,SOHR,Other,Unidentified gunmen kidnapped five members of ...,0,1624916983,SYR,1,1
8774,8754539,760,SYR39257,39257,2017,1,Battles,Armed clash,Military Forces of Syria (2000-),NaN,...,36.1979,1,SHAAM,National,Syrian regime forces attempted to advance duri...,0,1641867746,SYR,1,1
8775,8757446,760,SYR34474,34474,2017,1,Battles,Armed clash,Military Forces of Syria (2000-),NaN,...,36.1234,2,SHAAM,National,Syrian regime forces attempted to advance duri...,0,1641867755,SYR,1,1
8776,8758088,760,SYR39253,39253,2017,1,Battles,Armed clash,Opposition Rebels (Syria),NaN,...,36.4046,1,SHAAM,National,Clashes took place between rebels and Syrian r...,0,1641867757,SYR,1,1

In [11]:
# Export to CSV to be exported to GEOJSON in QGIS
#df2.to_csv("conflicts_syria_2017.csv", sep=',')